name: finance_dbt
version: '1.0.0'
config-version: 2

profile: finance_dbt

models:
  finance_dbt:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']